version: 2
jobs:
  push:
    machine:
      - image: circleci/classic:latest
    steps:
      - setup_remote_docker
      - run: make push
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
  jobs:
    - push
